### ISSUE TITLE
__qualname__ unsupported for Python versions < 3.3

### ISSUE THREAD

**Issue by rodricios** [eugene-eeo/closurepr#2]
Testing this module in 3.5.x, I get:

```
Python 3.5.1 |Anaconda 2.1.0 (64-bit)| (default, Jan 29 2016, 15:01:46) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from requests import get
>>> from libextract.api import extract
>>>
>>> r = get('http://en.wikipedia.org/wiki/Information_extraction')
>>> textnodes = list(extract(r.content))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\rodrigo\github\datalib\libextract\libextract\api.py", line 13, in extract
    parse_html(document, encoding=encoding),
  File "C:\Users\rodrigo\github\datalib\libextract\libextract\funcs\closurepr.py", line 24, in wrapper
    closure.__qualname__ = string
AttributeError: 'lxml.etree._ElementTree' object has no attribute '__qualname__'
```

Strangely enough, accessing `_ElementTree` explicitly does not produce the same error: 

```
>>> import lxml
>>> lxml.etree._ElementTree.__qualname__
'_ElementTree'
```

I'm using `@rich_repr` on practically all functions in this [module](https://github.com/datalib/libextract/blob/master/libextract/core.py). 

One solution is to use this module: [qualname](https://pypi.python.org/pypi/qualname/). [Related discussion](http://stackoverflow.com/questions/26544078/reproduce-effects-of-python-3-3-qualname-in-earlier-pythons)

**Comment by rodricios** [comment]
I figured out the problem: my understanding of what this does :P
